import akinator_model
import numpy as np

answers = ["Yes", "Maybe", "No"]
YES = 0
MAYBE = 1
NO = 2
        
def setup_character_akinator(akinator):
    defaultyes = [0.90, 0.05, 0.05]
    defaultmaybe = [0.2, 0.60, 0.2]
    defaultno = [0.05, 0.05, 0.90]
    
    qkey = akinator.addquestion("Are they male?")
    #akinator.addanswer(qkey, "Harry Potter", defaultyes)
    akinator.addanswer(qkey, "Donald Trump", defaultyes)
    akinator.addanswer(qkey, "Pikachu", defaultyes)
    akinator.addanswer(qkey, "Heidi", defaultno)
    akinator.addanswer(qkey, "Popeye", defaultyes)
    akinator.addanswer(qkey, "Queen Victoria", defaultno)
    akinator.addanswer(qkey, "PewDiePie", defaultyes)
    akinator.addanswer(qkey, "Britney Spears", defaultno)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.addanswer(qkey, "Gandalf", defaultyes)
    akinator.addanswer(qkey, "Hillary Clinton", defaultno)
    akinator.addanswer(qkey, "Nelson Mandela", defaultyes)
    akinator.addanswer(qkey, "Pythagoras", defaultyes)
    akinator.addanswer(qkey, "Spiderman", defaultyes)
    akinator.addanswer(qkey, "Albert Einstein", defaultyes)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.addanswer(qkey, "Marie Curie", defaultno)
    akinator.addanswer(qkey, "J. K. Rowling", defaultno)
    akinator.addanswer(qkey, "Usain Bolt", defaultyes)
    akinator.addanswer(qkey, "Bill Gates", defaultyes)
    akinator.addanswer(qkey, "Elon Musk", defaultyes)
    akinator.addanswer(qkey, "Julius Caesar", defaultyes)
    akinator.addanswer(qkey, "Pacman", defaultyes)
    akinator.addanswer(qkey, "Snow White", defaultno)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultyes)
    
    
    qkey = akinator.addquestion("Are they real?")
    akinator.addanswer(qkey, "Harry Potter", defaultno)
    akinator.addanswer(qkey, "Donald Trump", defaultyes)
    akinator.addanswer(qkey, "Pikachu", defaultno)
    akinator.addanswer(qkey, "Heidi", defaultno)
    akinator.addanswer(qkey, "Popeye", defaultno)
    akinator.addanswer(qkey, "Queen Victoria", defaultyes)
    akinator.addanswer(qkey, "PewDiePie", defaultyes)
    akinator.addanswer(qkey, "Britney Spears", defaultyes)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.addanswer(qkey, "Gandalf", defaultno)
    akinator.addanswer(qkey, "Hillary Clinton", defaultyes)
    akinator.addanswer(qkey, "Nelson Mandela", defaultyes)
    akinator.addanswer(qkey, "Pythagoras", defaultyes)
    akinator.addanswer(qkey, "Spiderman", defaultno)
    akinator.addanswer(qkey, "Albert Einstein", defaultyes)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultyes)
    akinator.addanswer(qkey, "Marie Curie", defaultyes)
    akinator.addanswer(qkey, "J. K. Rowling", defaultyes)
    akinator.addanswer(qkey, "Usain Bolt", defaultyes)
    akinator.addanswer(qkey, "Bill Gates", defaultyes)
    akinator.addanswer(qkey, "Elon Musk", defaultyes)
    akinator.addanswer(qkey, "Julius Caesar", defaultyes)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultno)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they animated?")
    akinator.addanswer(qkey, "Harry Potter", defaultno)
    akinator.addanswer(qkey, "Donald Trump", defaultno)
    akinator.addanswer(qkey, "Pikachu", defaultyes)
    akinator.addanswer(qkey, "Heidi", defaultmaybe)
    akinator.addanswer(qkey, "Popeye", defaultyes)
    akinator.addanswer(qkey, "Queen Victoria", defaultno)
    akinator.addanswer(qkey, "PewDiePie", defaultno)
    akinator.addanswer(qkey, "Britney Spears", defaultno)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.addanswer(qkey, "Gandalf", defaultno)
    akinator.addanswer(qkey, "Hillary Clinton", defaultno)
    akinator.addanswer(qkey, "Nelson Mandela", defaultno)
    akinator.addanswer(qkey, "Pythagoras", defaultno)
    akinator.addanswer(qkey, "Spiderman", defaultmaybe)
    akinator.addanswer(qkey, "Albert Einstein", defaultno)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.addanswer(qkey, "Marie Curie", defaultno)
    akinator.addanswer(qkey, "J. K. Rowling", defaultno)
    akinator.addanswer(qkey, "Usain Bolt", defaultno)
    akinator.addanswer(qkey, "Bill Gates", defaultno)
    akinator.addanswer(qkey, "Elon Musk", defaultno)
    akinator.addanswer(qkey, "Julius Caesar", defaultno)
    akinator.addanswer(qkey, "Pacman", defaultyes)
    akinator.addanswer(qkey, "Snow White", defaultyes)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultyes)
    
    qkey = akinator.addquestion("Are they tall?")
    akinator.addanswer(qkey, "Harry Potter", defaultmaybe)
    akinator.addanswer(qkey, "Donald Trump", defaultyes)
    akinator.addanswer(qkey, "Pikachu", defaultno)
    akinator.addanswer(qkey, "Heidi", defaultno)
    akinator.addanswer(qkey, "Popeye", defaultmaybe)
    akinator.addanswer(qkey, "Queen Victoria", defaultmaybe)
    akinator.addanswer(qkey, "PewDiePie", defaultmaybe)
    akinator.addanswer(qkey, "Britney Spears", defaultno)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.addanswer(qkey, "Gandalf", defaultyes)
    akinator.addanswer(qkey, "Hillary Clinton", defaultno)
    akinator.addanswer(qkey, "Nelson Mandela", defaultyes)
    akinator.addanswer(qkey, "Pythagoras", defaultmaybe)
    akinator.addanswer(qkey, "Spiderman", defaultmaybe)
    akinator.addanswer(qkey, "Albert Einstein", defaultmaybe)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultmaybe)
    akinator.addanswer(qkey, "Marie Curie", defaultmaybe)
    akinator.addanswer(qkey, "J. K. Rowling", defaultmaybe)
    akinator.addanswer(qkey, "Usain Bolt", defaultyes)
    akinator.addanswer(qkey, "Bill Gates", defaultmaybe)
    akinator.addanswer(qkey, "Elon Musk", defaultmaybe)
    akinator.addanswer(qkey, "Julius Caesar", defaultmaybe)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultmaybe)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they a YouTuber?")
    akinator.addanswer(qkey, "Harry Potter", defaultno)
    akinator.addanswer(qkey, "Donald Trump", defaultno)
    akinator.addanswer(qkey, "Pikachu", defaultno)
    akinator.addanswer(qkey, "Heidi", defaultno)
    akinator.addanswer(qkey, "Popeye", defaultno)
    akinator.addanswer(qkey, "Queen Victoria", defaultno)
    akinator.addanswer(qkey, "PewDiePie", defaultyes)
    akinator.addanswer(qkey, "Britney Spears", defaultno)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.addanswer(qkey, "Gandalf", defaultno)
    akinator.addanswer(qkey, "Hillary Clinton", defaultno)
    akinator.addanswer(qkey, "Nelson Mandela", defaultno)
    akinator.addanswer(qkey, "Pythagoras", defaultno)
    akinator.addanswer(qkey, "Spiderman", defaultno)
    akinator.addanswer(qkey, "Albert Einstein", defaultno)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.addanswer(qkey, "Marie Curie", defaultno)
    akinator.addanswer(qkey, "J. K. Rowling", defaultno)
    akinator.addanswer(qkey, "Usain Bolt", defaultno)
    akinator.addanswer(qkey, "Bill Gates", defaultno)
    akinator.addanswer(qkey, "Elon Musk", defaultno)
    akinator.addanswer(qkey, "Julius Caesar", defaultno)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultno)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they magic?")
    akinator.addanswer(qkey, "Harry Potter", defaultyes)
    akinator.addanswer(qkey, "Donald Trump", defaultno)
    akinator.addanswer(qkey, "Pikachu", defaultmaybe)
    akinator.addanswer(qkey, "Heidi", defaultno)
    akinator.addanswer(qkey, "Popeye", defaultno)
    akinator.addanswer(qkey, "Queen Victoria", defaultno)
    akinator.addanswer(qkey, "PewDiePie", defaultno)
    akinator.addanswer(qkey, "Britney Spears", defaultno)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.addanswer(qkey, "Gandalf", defaultyes)
    akinator.addanswer(qkey, "Hillary Clinton", defaultno)
    akinator.addanswer(qkey, "Nelson Mandela", defaultno)
    akinator.addanswer(qkey, "Pythagoras", defaultno)
    akinator.addanswer(qkey, "Spiderman", defaultno)
    akinator.addanswer(qkey, "Albert Einstein", defaultno)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.addanswer(qkey, "Marie Curie", defaultno)
    akinator.addanswer(qkey, "J. K. Rowling", defaultno)
    akinator.addanswer(qkey, "Usain Bolt", defaultno)
    akinator.addanswer(qkey, "Bill Gates", defaultno)
    akinator.addanswer(qkey, "Elon Musk", defaultno)
    akinator.addanswer(qkey, "Julius Caesar", defaultno)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultmaybe)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Do they have special powers?")
    akinator.addanswer(qkey, "Harry Potter", defaultyes)
    akinator.addanswer(qkey, "Donald Trump", defaultmaybe)
    akinator.addanswer(qkey, "Pikachu", defaultyes)
    akinator.addanswer(qkey, "Heidi", defaultno)
    akinator.addanswer(qkey, "Popeye", defaultyes)
    akinator.addanswer(qkey, "Queen Victoria", defaultmaybe)
    akinator.addanswer(qkey, "PewDiePie", defaultno)
    akinator.addanswer(qkey, "Britney Spears", defaultno)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.addanswer(qkey, "Gandalf", defaultyes)
    akinator.addanswer(qkey, "Hillary Clinton", defaultno)
    akinator.addanswer(qkey, "Nelson Mandela", defaultno)
    akinator.addanswer(qkey, "Pythagoras", defaultno)
    akinator.addanswer(qkey, "Spiderman", defaultyes)
    akinator.addanswer(qkey, "Albert Einstein", defaultno)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.addanswer(qkey, "Marie Curie", defaultno)
    akinator.addanswer(qkey, "J. K. Rowling", defaultno)
    akinator.addanswer(qkey, "Usain Bolt", defaultmaybe)
    akinator.addanswer(qkey, "Bill Gates", defaultno)
    akinator.addanswer(qkey, "Elon Musk", defaultno)
    akinator.addanswer(qkey, "Julius Caesar", defaultno)
    akinator.addanswer(qkey, "Pacman", defaultmaybe)
    akinator.addanswer(qkey, "Snow White", defaultno)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they alive?")
    akinator.addanswer(qkey, "Harry Potter", defaultno)
    akinator.addanswer(qkey, "Donald Trump", defaultyes)
    akinator.addanswer(qkey, "Pikachu", defaultno)
    akinator.addanswer(qkey, "Heidi", defaultno)
    akinator.addanswer(qkey, "Popeye", defaultno)
    akinator.addanswer(qkey, "Queen Victoria", defaultno)
    akinator.addanswer(qkey, "PewDiePie", defaultyes)
    akinator.addanswer(qkey, "Britney Spears", defaultyes)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.addanswer(qkey, "Gandalf", defaultno)
    akinator.addanswer(qkey, "Hillary Clinton", defaultyes)
    akinator.addanswer(qkey, "Nelson Mandela", defaultno)
    akinator.addanswer(qkey, "Pythagoras", defaultno)
    akinator.addanswer(qkey, "Spiderman", defaultno)
    akinator.addanswer(qkey, "Albert Einstein", defaultno)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.addanswer(qkey, "Marie Curie", defaultno)
    akinator.addanswer(qkey, "J. K. Rowling", defaultyes)
    akinator.addanswer(qkey, "Usain Bolt", defaultyes)
    akinator.addanswer(qkey, "Bill Gates", defaultyes)
    akinator.addanswer(qkey, "Elon Musk", defaultyes)
    akinator.addanswer(qkey, "Julius Caesar", defaultno)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultno)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they a child?")
    akinator.addanswer(qkey, "Harry Potter", defaultmaybe)
    akinator.addanswer(qkey, "Donald Trump", defaultno)
    akinator.addanswer(qkey, "Pikachu", defaultmaybe)
    akinator.addanswer(qkey, "Heidi", defaultyes)
    akinator.addanswer(qkey, "Popeye", defaultno)
    akinator.addanswer(qkey, "Queen Victoria", defaultno)
    akinator.addanswer(qkey, "PewDiePie", defaultno)
    akinator.addanswer(qkey, "Britney Spears", defaultno)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.addanswer(qkey, "Gandalf", defaultno)
    akinator.addanswer(qkey, "Hillary Clinton", defaultno)
    akinator.addanswer(qkey, "Nelson Mandela", defaultno)
    akinator.addanswer(qkey, "Pythagoras", defaultno)
    akinator.addanswer(qkey, "Spiderman", defaultno)
    akinator.addanswer(qkey, "Albert Einstein", defaultno)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.addanswer(qkey, "Marie Curie", defaultno)
    akinator.addanswer(qkey, "J. K. Rowling", defaultno)
    akinator.addanswer(qkey, "Usain Bolt", defaultno)
    akinator.addanswer(qkey, "Bill Gates", defaultno)
    akinator.addanswer(qkey, "Elon Musk", defaultno)
    akinator.addanswer(qkey, "Julius Caesar", defaultno)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultmaybe)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultyes)
    
    qkey = akinator.addquestion("Are they human?")
    akinator.addanswer(qkey, "Harry Potter", defaultyes)
    akinator.addanswer(qkey, "Donald Trump", defaultyes)
    akinator.addanswer(qkey, "Pikachu", defaultno)
    akinator.addanswer(qkey, "Heidi", defaultyes)
    akinator.addanswer(qkey, "Popeye", defaultyes)
    akinator.addanswer(qkey, "Queen Victoria", defaultyes)
    akinator.addanswer(qkey, "PewDiePie", defaultyes)
    akinator.addanswer(qkey, "Britney Spears", defaultyes)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.addanswer(qkey, "Gandalf", defaultmaybe)
    akinator.addanswer(qkey, "Hillary Clinton", defaultyes)
    akinator.addanswer(qkey, "Nelson Mandela", defaultyes)
    akinator.addanswer(qkey, "Pythagoras", defaultyes)
    akinator.addanswer(qkey, "Spiderman", defaultyes)
    akinator.addanswer(qkey, "Albert Einstein", defaultyes)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultyes)
    akinator.addanswer(qkey, "Marie Curie", defaultyes)
    akinator.addanswer(qkey, "J. K. Rowling", defaultyes)
    akinator.addanswer(qkey, "Usain Bolt", defaultyes)
    akinator.addanswer(qkey, "Bill Gates", defaultyes)
    akinator.addanswer(qkey, "Elon Musk", defaultyes)
    akinator.addanswer(qkey, "Julius Caesar", defaultyes)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultyes)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultyes)
    
    qkey = akinator.addquestion("Are they popular with children?")
    akinator.addanswer(qkey, "Harry Potter", defaultyes)
    akinator.addanswer(qkey, "Donald Trump", defaultno)
    akinator.addanswer(qkey, "Pikachu", defaultyes)
    akinator.addanswer(qkey, "Heidi", defaultyes)
    akinator.addanswer(qkey, "Popeye", defaultyes)
    akinator.addanswer(qkey, "Queen Victoria", defaultno)
    akinator.addanswer(qkey, "PewDiePie", defaultyes)
    akinator.addanswer(qkey, "Britney Spears", defaultmaybe)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.addanswer(qkey, "Gandalf", defaultmaybe)
    akinator.addanswer(qkey, "Hillary Clinton", defaultno)
    akinator.addanswer(qkey, "Nelson Mandela", defaultmaybe)
    akinator.addanswer(qkey, "Pythagoras", defaultno)
    akinator.addanswer(qkey, "Spiderman", defaultyes)
    akinator.addanswer(qkey, "Albert Einstein", defaultno)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.addanswer(qkey, "Marie Curie", defaultno)
    akinator.addanswer(qkey, "J. K. Rowling", defaultyes)
    akinator.addanswer(qkey, "Usain Bolt", defaultmaybe)
    akinator.addanswer(qkey, "Bill Gates", defaultno)
    akinator.addanswer(qkey, "Elon Musk", defaultno)
    akinator.addanswer(qkey, "Julius Caesar", defaultno)
    akinator.addanswer(qkey, "Pacman", defaultyes)
    akinator.addanswer(qkey, "Snow White", defaultyes)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultyes)
    
    qkey = akinator.addquestion("Are they an entertainer?")
    akinator.addanswer(qkey, "Harry Potter", defaultno)
    akinator.addanswer(qkey, "Donald Trump", defaultmaybe)
    akinator.addanswer(qkey, "Pikachu", defaultno)
    akinator.addanswer(qkey, "Heidi", defaultno)
    akinator.addanswer(qkey, "Popeye", defaultno)
    akinator.addanswer(qkey, "Queen Victoria", defaultno)
    akinator.addanswer(qkey, "PewDiePie", defaultyes)
    akinator.addanswer(qkey, "Britney Spears", defaultyes)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.addanswer(qkey, "Gandalf", defaultno)
    akinator.addanswer(qkey, "Hillary Clinton", defaultno)
    akinator.addanswer(qkey, "Nelson Mandela", defaultno)
    akinator.addanswer(qkey, "Pythagoras", defaultno)
    akinator.addanswer(qkey, "Spiderman", defaultno)
    akinator.addanswer(qkey, "Albert Einstein", defaultno)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultyes)
    akinator.addanswer(qkey, "Marie Curie", defaultno)
    akinator.addanswer(qkey, "J. K. Rowling", defaultno)
    akinator.addanswer(qkey, "Usain Bolt", defaultno)
    akinator.addanswer(qkey, "Bill Gates", defaultno)
    akinator.addanswer(qkey, "Elon Musk", defaultno)
    akinator.addanswer(qkey, "Julius Caesar", defaultno)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultno)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they a politician?")
    akinator.addanswer(qkey, "Harry Potter", defaultno)
    akinator.addanswer(qkey, "Donald Trump", defaultyes)
    akinator.addanswer(qkey, "Pikachu", defaultno)
    akinator.addanswer(qkey, "Heidi", defaultno)
    akinator.addanswer(qkey, "Popeye", defaultno)
    akinator.addanswer(qkey, "Queen Victoria", defaultmaybe)
    akinator.addanswer(qkey, "PewDiePie", defaultno)
    akinator.addanswer(qkey, "Britney Spears", defaultno)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.addanswer(qkey, "Gandalf", defaultno)
    akinator.addanswer(qkey, "Hillary Clinton", defaultyes)
    akinator.addanswer(qkey, "Nelson Mandela", defaultyes)
    akinator.addanswer(qkey, "Pythagoras", defaultno)
    akinator.addanswer(qkey, "Spiderman", defaultno)
    akinator.addanswer(qkey, "Albert Einstein", defaultno)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.addanswer(qkey, "Marie Curie", defaultno)
    akinator.addanswer(qkey, "J. K. Rowling", defaultno)
    akinator.addanswer(qkey, "Usain Bolt", defaultno)
    akinator.addanswer(qkey, "Bill Gates", defaultno)
    akinator.addanswer(qkey, "Elon Musk", defaultno)
    akinator.addanswer(qkey, "Julius Caesar", defaultmaybe)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultno)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they American?")
    akinator.addanswer(qkey, "Harry Potter", defaultno)
    akinator.addanswer(qkey, "Donald Trump", defaultyes)
    akinator.addanswer(qkey, "Pikachu", defaultno)
    akinator.addanswer(qkey, "Heidi", defaultno)
    akinator.addanswer(qkey, "Popeye", defaultyes)
    akinator.addanswer(qkey, "Queen Victoria", defaultno)
    akinator.addanswer(qkey, "PewDiePie", defaultno)
    akinator.addanswer(qkey, "Britney Spears", defaultyes)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.addanswer(qkey, "Gandalf", defaultno)
    akinator.addanswer(qkey, "Hillary Clinton", defaultyes)
    akinator.addanswer(qkey, "Nelson Mandela", defaultno)
    akinator.addanswer(qkey, "Pythagoras", defaultno)
    akinator.addanswer(qkey, "Spiderman", defaultyes)
    akinator.addanswer(qkey, "Albert Einstein", defaultmaybe)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultyes)
    akinator.addanswer(qkey, "Marie Curie", defaultno)
    akinator.addanswer(qkey, "J. K. Rowling", defaultno)
    akinator.addanswer(qkey, "Usain Bolt", defaultno)
    akinator.addanswer(qkey, "Bill Gates", defaultyes)
    akinator.addanswer(qkey, "Elon Musk", defaultmaybe)
    akinator.addanswer(qkey, "Julius Caesar", defaultno)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultno)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they considered attractive?")
    akinator.addanswer(qkey, "Harry Potter", defaultmaybe)
    akinator.addanswer(qkey, "Donald Trump", defaultno)
    akinator.addanswer(qkey, "Pikachu", defaultno)
    akinator.addanswer(qkey, "Heidi", defaultno)
    akinator.addanswer(qkey, "Popeye", defaultmaybe)
    akinator.addanswer(qkey, "Queen Victoria", defaultno)
    akinator.addanswer(qkey, "PewDiePie", defaultmaybe)
    akinator.addanswer(qkey, "Britney Spears", defaultmaybe)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.addanswer(qkey, "Gandalf", defaultno)
    akinator.addanswer(qkey, "Hillary Clinton", defaultno)
    akinator.addanswer(qkey, "Nelson Mandela", defaultno)
    akinator.addanswer(qkey, "Pythagoras", defaultno)
    akinator.addanswer(qkey, "Spiderman", defaultyes)
    akinator.addanswer(qkey, "Albert Einstein", defaultno)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultyes)
    akinator.addanswer(qkey, "Marie Curie", defaultno)
    akinator.addanswer(qkey, "J. K. Rowling", defaultmaybe)
    akinator.addanswer(qkey, "Usain Bolt", defaultmaybe)
    akinator.addanswer(qkey, "Bill Gates", defaultno)
    akinator.addanswer(qkey, "Elon Musk", defaultmaybe)
    akinator.addanswer(qkey, "Julius Caesar", defaultno)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultyes)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are the considered intelligent or wise?")
    akinator.addanswer(qkey, "Harry Potter", defaultno)
    akinator.addanswer(qkey, "Donald Trump", defaultno)
    akinator.addanswer(qkey, "Pikachu", defaultno)
    akinator.addanswer(qkey, "Heidi", defaultno)
    akinator.addanswer(qkey, "Popeye", defaultno)
    akinator.addanswer(qkey, "Queen Victoria", defaultyes)
    akinator.addanswer(qkey, "PewDiePie", defaultno)
    akinator.addanswer(qkey, "Britney Spears", defaultno)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.addanswer(qkey, "Gandalf", defaultyes)
    akinator.addanswer(qkey, "Hillary Clinton", defaultmaybe)
    akinator.addanswer(qkey, "Nelson Mandela", defaultmaybe)
    akinator.addanswer(qkey, "Pythagoras", defaultyes)
    akinator.addanswer(qkey, "Spiderman", defaultno)
    akinator.addanswer(qkey, "Albert Einstein", defaultyes)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultmaybe)
    akinator.addanswer(qkey, "Marie Curie", defaultyes)
    akinator.addanswer(qkey, "J. K. Rowling", defaultyes)
    akinator.addanswer(qkey, "Usain Bolt", defaultmaybe)
    akinator.addanswer(qkey, "Bill Gates", defaultyes)
    akinator.addanswer(qkey, "Elon Musk", defaultyes)
    akinator.addanswer(qkey, "Julius Caesar", defaultmaybe)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultno)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Did they live in ancient times?")
    akinator.addanswer(qkey, "Harry Potter", defaultno)
    akinator.addanswer(qkey, "Donald Trump", defaultno)
    akinator.addanswer(qkey, "Pikachu", defaultno)
    akinator.addanswer(qkey, "Heidi", defaultno)
    akinator.addanswer(qkey, "Popeye", defaultno)
    akinator.addanswer(qkey, "Queen Victoria", defaultno)
    akinator.addanswer(qkey, "PewDiePie", defaultno)
    akinator.addanswer(qkey, "Britney Spears", defaultno)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.addanswer(qkey, "Gandalf", defaultmaybe)
    akinator.addanswer(qkey, "Hillary Clinton", defaultno)
    akinator.addanswer(qkey, "Nelson Mandela", defaultno)
    akinator.addanswer(qkey, "Pythagoras", defaultyes)
    akinator.addanswer(qkey, "Spiderman", defaultno)
    akinator.addanswer(qkey, "Albert Einstein", defaultno)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.addanswer(qkey, "Marie Curie", defaultno)
    akinator.addanswer(qkey, "J. K. Rowling", defaultno)
    akinator.addanswer(qkey, "Usain Bolt", defaultno)
    akinator.addanswer(qkey, "Bill Gates", defaultno)
    akinator.addanswer(qkey, "Elon Musk", defaultno)
    akinator.addanswer(qkey, "Julius Caesar", defaultyes)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultmaybe)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they a scientist or mathematician?")
    akinator.addanswer(qkey, "Harry Potter", defaultno)
    akinator.addanswer(qkey, "Donald Trump", defaultno)
    akinator.addanswer(qkey, "Pikachu", defaultno)
    akinator.addanswer(qkey, "Heidi", defaultno)
    akinator.addanswer(qkey, "Popeye", defaultno)
    akinator.addanswer(qkey, "Queen Victoria", defaultno)
    akinator.addanswer(qkey, "PewDiePie", defaultno)
    akinator.addanswer(qkey, "Britney Spears", defaultno)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.addanswer(qkey, "Gandalf", defaultno)
    akinator.addanswer(qkey, "Hillary Clinton", defaultno)
    akinator.addanswer(qkey, "Nelson Mandela", defaultno)
    akinator.addanswer(qkey, "Pythagoras", defaultyes)
    akinator.addanswer(qkey, "Spiderman", defaultno)
    akinator.addanswer(qkey, "Albert Einstein", defaultyes)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.addanswer(qkey, "Marie Curie", defaultyes)
    akinator.addanswer(qkey, "J. K. Rowling", defaultno)
    akinator.addanswer(qkey, "Usain Bolt", defaultno)
    akinator.addanswer(qkey, "Bill Gates", defaultmaybe)
    akinator.addanswer(qkey, "Elon Musk", defaultmaybe)
    akinator.addanswer(qkey, "Julius Caesar", defaultno)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultno)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they based on an animal?")
    akinator.addanswer(qkey, "Harry Potter", defaultno)
    akinator.addanswer(qkey, "Donald Trump", defaultno)
    akinator.addanswer(qkey, "Pikachu", defaultyes)
    akinator.addanswer(qkey, "Heidi", defaultno)
    akinator.addanswer(qkey, "Popeye", defaultno)
    akinator.addanswer(qkey, "Queen Victoria", defaultno)
    akinator.addanswer(qkey, "PewDiePie", defaultno)
    akinator.addanswer(qkey, "Britney Spears", defaultno)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.addanswer(qkey, "Gandalf", defaultno)
    akinator.addanswer(qkey, "Hillary Clinton", defaultno)
    akinator.addanswer(qkey, "Nelson Mandela", defaultno)
    akinator.addanswer(qkey, "Pythagoras", defaultno)
    akinator.addanswer(qkey, "Spiderman", defaultyes)
    akinator.addanswer(qkey, "Albert Einstein", defaultno)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.addanswer(qkey, "Marie Curie", defaultno)
    akinator.addanswer(qkey, "J. K. Rowling", defaultno)
    akinator.addanswer(qkey, "Usain Bolt", defaultno)
    akinator.addanswer(qkey, "Bill Gates", defaultno)
    akinator.addanswer(qkey, "Elon Musk", defaultno)
    akinator.addanswer(qkey, "Julius Caesar", defaultno)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultno)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Do they appear as a main character in a movie?")
    akinator.addanswer(qkey, "Harry Potter", defaultyes)
    akinator.addanswer(qkey, "Donald Trump", defaultno)
    akinator.addanswer(qkey, "Pikachu", defaultyes)
    akinator.addanswer(qkey, "Heidi", defaultyes)
    akinator.addanswer(qkey, "Popeye", defaultyes)
    akinator.addanswer(qkey, "Queen Victoria", defaultyes)
    akinator.addanswer(qkey, "PewDiePie", defaultno)
    akinator.addanswer(qkey, "Britney Spears", defaultno)
    akinator.addanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.addanswer(qkey, "Gandalf", defaultyes)
    akinator.addanswer(qkey, "Hillary Clinton", defaultno)
    akinator.addanswer(qkey, "Nelson Mandela", defaultyes)
    akinator.addanswer(qkey, "Pythagoras", defaultno)
    akinator.addanswer(qkey, "Spiderman", defaultyes)
    akinator.addanswer(qkey, "Albert Einstein", defaultno)
    akinator.addanswer(qkey, "Marilyn Monroe", defaultyes)
    akinator.addanswer(qkey, "Marie Curie", defaultno)
    akinator.addanswer(qkey, "J. K. Rowling", defaultno)
    akinator.addanswer(qkey, "Usain Bolt", defaultno)
    akinator.addanswer(qkey, "Bill Gates", defaultno)
    akinator.addanswer(qkey, "Elon Musk", defaultno)
    akinator.addanswer(qkey, "Julius Caesar", defaultyes)
    akinator.addanswer(qkey, "Pacman", defaultno)
    akinator.addanswer(qkey, "Snow White", defaultyes)
    akinator.addanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultyes)
    
    for (state,qkey) in akinator.answerdict:
        if state not in akinator.states:
            akinator.states.append(state)
    akinator.numstates = len(akinator.states)
    print("States: %d, questions %d" % (akinator.numstates, len(akinator.questions)))
    
    """
    for state in states:
        qkey = akinator.addquestion("Is your state %s?" % state)
        for c in states:
            akinator.answerdict[(c,qkey)] = [0.005, 0.005, 0.99]
        akinator.answerdict[(state,qkey)] = [0.99, 0.005, 0.005] 
    """
    akinator.stateprobs = np.ones(shape=(akinator.numstates))/akinator.numstates
    akinator.statelogprobs = np.ones(shape=(akinator.numstates))*-np.log(akinator.numstates)

if __name__== "__main__":    
    akinator = akinator_model.Akinator()
    setup_character_akinator(akinator)
    questionno = 1
    while True:    
        qkey = akinator.getnextquestion()
        if qkey < 0:
            break
        akinator.usedquestions.append(qkey)
        answer = input("Q%d: %s " % (questionno, akinator.questions[qkey])).upper()
        akey = -1
        if answer.startswith("Y"):
            akey = YES
        elif answer.startswith("M"):
            akey = MAYBE
        elif answer.startswith("N"):
            akey = NO
        else:
            break
        akinator.update(qkey, akey)
        questionno += 1

