# -*- coding: utf-8 -*-
"""
Created on Thu Jun 20 15:58:24 2019

@author: Michael
"""
import numpy as np

answers = ["Yes", "Maybe", "No"]
YES = 0
MAYBE = 1
NO = 2

defaultyes = [0.90, 0.05, 0.05]
defaultmaybe = [0.2, 0.60, 0.2]
defaultno = [0.05, 0.05, 0.90]
class Akinator:
    def __init__(self):
        self.questions = []
        self.answerdict = {}
        self.characters = []
        self.numcharacters = 0        
        self.stateprobs = None
        self.statelogprobs = None
        self.usedquestions = []
        
    def addquestion(self, question):
        qkey = len(self.questions)
        self.questions.append(question)
        return qkey
    
    def update(self, qkey, akey):
        avec = np.zeros(3)
        avec[akey] = 1.0 # create an answer probability vector with no input noise
        self.update_helper(qkey, avec)
    
    def update_helper(self, qkey, avec): # avec is an answer probability vector, where the probabilities reflect potential input noise
        self.statelogprobs, self.stateprobs = self.calculate_state_probs(self.statelogprobs, self.stateprobs, qkey, avec)
        sortedcharacters = [(p, character) for (p, character)  in zip(self.stateprobs,self.characters)]
        sortedcharacters.sort()
        for (p, character) in sortedcharacters:
            print(" %s: %0.6f" % (character,p))
        print(self.statelogprobs)
        print(np.sum(self.stateprobs))
        print("------------------------------")
        
    def calculate_state_probs(self, statelogprobs, stateprobs, qkey, avec):
        
        hasquestionlogsum = -np.inf
        noquestionlogsum = -np.inf
        for ckey in range(self.numcharacters):
            characterquestionkey = (self.characters[ckey],qkey)
            if characterquestionkey in self.answerdict:
                likelihood = np.dot(self.answerdict[characterquestionkey],avec)            
                v = np.log(likelihood) + statelogprobs[ckey]
                statelogprobs[ckey] = v
                hasquestionlogsum = np.logaddexp(hasquestionlogsum, v)
            else:
                noquestionlogsum = np.logaddexp(noquestionlogsum, statelogprobs[ckey])
                print("No question for character %s" % self.characters[ckey])
        
        
        logsum = -np.inf
        # if one or more characters don't have a particular question, keep their marginal probability the same by multiplying the characters with the question by the following quantity:
        hasquestionmultiplier = np.log(1.0 - np.exp(noquestionlogsum))
        for ckey in range(self.numcharacters):
            characterquestionkey = (self.characters[ckey],qkey)
            if characterquestionkey in self.answerdict:
                statelogprobs[ckey] += hasquestionmultiplier-hasquestionlogsum           
            logsum = np.logaddexp(logsum, statelogprobs[ckey]) # normalisation constant
                
        statelogprobs -= logsum
        stateprobs = np.exp(statelogprobs)
        
        return statelogprobs, stateprobs
        
    def nextquestion_entropy(self):
        expectedentropies = np.zeros(shape=len(self.questions))
        for qkey in range(len(self.questions)):
            expectedentropy = 0.0
            for akey in range(len(answers)):
                avec = np.zeros(3)
                avec[akey] = 1.0 # create an answer probability vector with no input noise
                tempstatelogprobs,tempstateprobs = self.calculate_state_probs(np.copy(self.statelogprobs), np.copy(self.stateprobs), qkey, avec)
                
                entropy = 0.0
                for (logp,p) in zip(tempstatelogprobs, tempstateprobs):
                    entropy += -p*logp
                for ckey in range(self.numcharacters):
                    characterquestionkey = (self.characters[ckey],qkey)
                    condanswerprob = 1.0/len(answers) # use a flat answer prior if this character doesn't have this question
                    if characterquestionkey in self.answerdict:
                        condanswerprob = self.answerdict[characterquestionkey][akey]
                    expectedentropy += entropy*condanswerprob*self.stateprobs[ckey]
                    
            expectedentropies[qkey] = expectedentropy
            #print("Q%d: %s (expected: %0.7f" % (qkey, questions[qkey], expectedentropy))
        minentropy = np.inf
        minindex = -1
        for qkey in range(len(self.questions)):
            if expectedentropies[qkey] < minentropy and qkey not in self.usedquestions:
                minentropy = expectedentropies[qkey]
                minindex = qkey
        return minindex
    
    def setanswer(self, qkey, charactername, answervec):
        self.answerdict[(charactername,qkey)] = answervec
        
def initialise(akinator):
    qkey = akinator.addquestion("Are they male?")
    #akinator.setanswer(qkey, "Harry Potter", defaultyes)
    akinator.setanswer(qkey, "Donald Trump", defaultyes)
    akinator.setanswer(qkey, "Pikachu", defaultyes)
    akinator.setanswer(qkey, "Heidi", defaultno)
    akinator.setanswer(qkey, "Popeye", defaultyes)
    akinator.setanswer(qkey, "Queen Victoria", defaultno)
    akinator.setanswer(qkey, "PewDiePie", defaultyes)
    akinator.setanswer(qkey, "Britney Spears", defaultno)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.setanswer(qkey, "Gandalf", defaultyes)
    akinator.setanswer(qkey, "Hillary Clinton", defaultno)
    akinator.setanswer(qkey, "Nelson Mandela", defaultyes)
    akinator.setanswer(qkey, "Pythagoras", defaultyes)
    akinator.setanswer(qkey, "Spiderman", defaultyes)
    akinator.setanswer(qkey, "Albert Einstein", defaultyes)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.setanswer(qkey, "Marie Curie", defaultno)
    akinator.setanswer(qkey, "J. K. Rowling", defaultno)
    akinator.setanswer(qkey, "Usain Bolt", defaultyes)
    akinator.setanswer(qkey, "Bill Gates", defaultyes)
    akinator.setanswer(qkey, "Elon Musk", defaultyes)
    akinator.setanswer(qkey, "Julius Caesar", defaultyes)
    akinator.setanswer(qkey, "Pacman", defaultyes)
    akinator.setanswer(qkey, "Snow White", defaultno)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultyes)
    
    
    qkey = akinator.addquestion("Are they real?")
    akinator.setanswer(qkey, "Harry Potter", defaultno)
    akinator.setanswer(qkey, "Donald Trump", defaultyes)
    akinator.setanswer(qkey, "Pikachu", defaultno)
    akinator.setanswer(qkey, "Heidi", defaultno)
    akinator.setanswer(qkey, "Popeye", defaultno)
    akinator.setanswer(qkey, "Queen Victoria", defaultyes)
    akinator.setanswer(qkey, "PewDiePie", defaultyes)
    akinator.setanswer(qkey, "Britney Spears", defaultyes)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.setanswer(qkey, "Gandalf", defaultno)
    akinator.setanswer(qkey, "Hillary Clinton", defaultyes)
    akinator.setanswer(qkey, "Nelson Mandela", defaultyes)
    akinator.setanswer(qkey, "Pythagoras", defaultyes)
    akinator.setanswer(qkey, "Spiderman", defaultno)
    akinator.setanswer(qkey, "Albert Einstein", defaultyes)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultyes)
    akinator.setanswer(qkey, "Marie Curie", defaultyes)
    akinator.setanswer(qkey, "J. K. Rowling", defaultyes)
    akinator.setanswer(qkey, "Usain Bolt", defaultyes)
    akinator.setanswer(qkey, "Bill Gates", defaultyes)
    akinator.setanswer(qkey, "Elon Musk", defaultyes)
    akinator.setanswer(qkey, "Julius Caesar", defaultyes)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultno)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they animated?")
    akinator.setanswer(qkey, "Harry Potter", defaultno)
    akinator.setanswer(qkey, "Donald Trump", defaultno)
    akinator.setanswer(qkey, "Pikachu", defaultyes)
    akinator.setanswer(qkey, "Heidi", defaultmaybe)
    akinator.setanswer(qkey, "Popeye", defaultyes)
    akinator.setanswer(qkey, "Queen Victoria", defaultno)
    akinator.setanswer(qkey, "PewDiePie", defaultno)
    akinator.setanswer(qkey, "Britney Spears", defaultno)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.setanswer(qkey, "Gandalf", defaultno)
    akinator.setanswer(qkey, "Hillary Clinton", defaultno)
    akinator.setanswer(qkey, "Nelson Mandela", defaultno)
    akinator.setanswer(qkey, "Pythagoras", defaultno)
    akinator.setanswer(qkey, "Spiderman", defaultmaybe)
    akinator.setanswer(qkey, "Albert Einstein", defaultno)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.setanswer(qkey, "Marie Curie", defaultno)
    akinator.setanswer(qkey, "J. K. Rowling", defaultno)
    akinator.setanswer(qkey, "Usain Bolt", defaultno)
    akinator.setanswer(qkey, "Bill Gates", defaultno)
    akinator.setanswer(qkey, "Elon Musk", defaultno)
    akinator.setanswer(qkey, "Julius Caesar", defaultno)
    akinator.setanswer(qkey, "Pacman", defaultyes)
    akinator.setanswer(qkey, "Snow White", defaultyes)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultyes)
    
    qkey = akinator.addquestion("Are they tall?")
    akinator.setanswer(qkey, "Harry Potter", defaultmaybe)
    akinator.setanswer(qkey, "Donald Trump", defaultyes)
    akinator.setanswer(qkey, "Pikachu", defaultno)
    akinator.setanswer(qkey, "Heidi", defaultno)
    akinator.setanswer(qkey, "Popeye", defaultmaybe)
    akinator.setanswer(qkey, "Queen Victoria", defaultmaybe)
    akinator.setanswer(qkey, "PewDiePie", defaultmaybe)
    akinator.setanswer(qkey, "Britney Spears", defaultno)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.setanswer(qkey, "Gandalf", defaultyes)
    akinator.setanswer(qkey, "Hillary Clinton", defaultno)
    akinator.setanswer(qkey, "Nelson Mandela", defaultyes)
    akinator.setanswer(qkey, "Pythagoras", defaultmaybe)
    akinator.setanswer(qkey, "Spiderman", defaultmaybe)
    akinator.setanswer(qkey, "Albert Einstein", defaultmaybe)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultmaybe)
    akinator.setanswer(qkey, "Marie Curie", defaultmaybe)
    akinator.setanswer(qkey, "J. K. Rowling", defaultmaybe)
    akinator.setanswer(qkey, "Usain Bolt", defaultyes)
    akinator.setanswer(qkey, "Bill Gates", defaultmaybe)
    akinator.setanswer(qkey, "Elon Musk", defaultmaybe)
    akinator.setanswer(qkey, "Julius Caesar", defaultmaybe)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultmaybe)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they a YouTuber?")
    akinator.setanswer(qkey, "Harry Potter", defaultno)
    akinator.setanswer(qkey, "Donald Trump", defaultno)
    akinator.setanswer(qkey, "Pikachu", defaultno)
    akinator.setanswer(qkey, "Heidi", defaultno)
    akinator.setanswer(qkey, "Popeye", defaultno)
    akinator.setanswer(qkey, "Queen Victoria", defaultno)
    akinator.setanswer(qkey, "PewDiePie", defaultyes)
    akinator.setanswer(qkey, "Britney Spears", defaultno)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.setanswer(qkey, "Gandalf", defaultno)
    akinator.setanswer(qkey, "Hillary Clinton", defaultno)
    akinator.setanswer(qkey, "Nelson Mandela", defaultno)
    akinator.setanswer(qkey, "Pythagoras", defaultno)
    akinator.setanswer(qkey, "Spiderman", defaultno)
    akinator.setanswer(qkey, "Albert Einstein", defaultno)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.setanswer(qkey, "Marie Curie", defaultno)
    akinator.setanswer(qkey, "J. K. Rowling", defaultno)
    akinator.setanswer(qkey, "Usain Bolt", defaultno)
    akinator.setanswer(qkey, "Bill Gates", defaultno)
    akinator.setanswer(qkey, "Elon Musk", defaultno)
    akinator.setanswer(qkey, "Julius Caesar", defaultno)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultno)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they magic?")
    akinator.setanswer(qkey, "Harry Potter", defaultyes)
    akinator.setanswer(qkey, "Donald Trump", defaultno)
    akinator.setanswer(qkey, "Pikachu", defaultmaybe)
    akinator.setanswer(qkey, "Heidi", defaultno)
    akinator.setanswer(qkey, "Popeye", defaultno)
    akinator.setanswer(qkey, "Queen Victoria", defaultno)
    akinator.setanswer(qkey, "PewDiePie", defaultno)
    akinator.setanswer(qkey, "Britney Spears", defaultno)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.setanswer(qkey, "Gandalf", defaultyes)
    akinator.setanswer(qkey, "Hillary Clinton", defaultno)
    akinator.setanswer(qkey, "Nelson Mandela", defaultno)
    akinator.setanswer(qkey, "Pythagoras", defaultno)
    akinator.setanswer(qkey, "Spiderman", defaultno)
    akinator.setanswer(qkey, "Albert Einstein", defaultno)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.setanswer(qkey, "Marie Curie", defaultno)
    akinator.setanswer(qkey, "J. K. Rowling", defaultno)
    akinator.setanswer(qkey, "Usain Bolt", defaultno)
    akinator.setanswer(qkey, "Bill Gates", defaultno)
    akinator.setanswer(qkey, "Elon Musk", defaultno)
    akinator.setanswer(qkey, "Julius Caesar", defaultno)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultmaybe)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Do they have special powers?")
    akinator.setanswer(qkey, "Harry Potter", defaultyes)
    akinator.setanswer(qkey, "Donald Trump", defaultmaybe)
    akinator.setanswer(qkey, "Pikachu", defaultyes)
    akinator.setanswer(qkey, "Heidi", defaultno)
    akinator.setanswer(qkey, "Popeye", defaultyes)
    akinator.setanswer(qkey, "Queen Victoria", defaultmaybe)
    akinator.setanswer(qkey, "PewDiePie", defaultno)
    akinator.setanswer(qkey, "Britney Spears", defaultno)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.setanswer(qkey, "Gandalf", defaultyes)
    akinator.setanswer(qkey, "Hillary Clinton", defaultno)
    akinator.setanswer(qkey, "Nelson Mandela", defaultno)
    akinator.setanswer(qkey, "Pythagoras", defaultno)
    akinator.setanswer(qkey, "Spiderman", defaultyes)
    akinator.setanswer(qkey, "Albert Einstein", defaultno)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.setanswer(qkey, "Marie Curie", defaultno)
    akinator.setanswer(qkey, "J. K. Rowling", defaultno)
    akinator.setanswer(qkey, "Usain Bolt", defaultmaybe)
    akinator.setanswer(qkey, "Bill Gates", defaultno)
    akinator.setanswer(qkey, "Elon Musk", defaultno)
    akinator.setanswer(qkey, "Julius Caesar", defaultno)
    akinator.setanswer(qkey, "Pacman", defaultmaybe)
    akinator.setanswer(qkey, "Snow White", defaultno)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they alive?")
    akinator.setanswer(qkey, "Harry Potter", defaultno)
    akinator.setanswer(qkey, "Donald Trump", defaultyes)
    akinator.setanswer(qkey, "Pikachu", defaultno)
    akinator.setanswer(qkey, "Heidi", defaultno)
    akinator.setanswer(qkey, "Popeye", defaultno)
    akinator.setanswer(qkey, "Queen Victoria", defaultno)
    akinator.setanswer(qkey, "PewDiePie", defaultyes)
    akinator.setanswer(qkey, "Britney Spears", defaultyes)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.setanswer(qkey, "Gandalf", defaultno)
    akinator.setanswer(qkey, "Hillary Clinton", defaultyes)
    akinator.setanswer(qkey, "Nelson Mandela", defaultno)
    akinator.setanswer(qkey, "Pythagoras", defaultno)
    akinator.setanswer(qkey, "Spiderman", defaultno)
    akinator.setanswer(qkey, "Albert Einstein", defaultno)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.setanswer(qkey, "Marie Curie", defaultno)
    akinator.setanswer(qkey, "J. K. Rowling", defaultyes)
    akinator.setanswer(qkey, "Usain Bolt", defaultyes)
    akinator.setanswer(qkey, "Bill Gates", defaultyes)
    akinator.setanswer(qkey, "Elon Musk", defaultyes)
    akinator.setanswer(qkey, "Julius Caesar", defaultno)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultno)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they a child?")
    akinator.setanswer(qkey, "Harry Potter", defaultmaybe)
    akinator.setanswer(qkey, "Donald Trump", defaultno)
    akinator.setanswer(qkey, "Pikachu", defaultmaybe)
    akinator.setanswer(qkey, "Heidi", defaultyes)
    akinator.setanswer(qkey, "Popeye", defaultno)
    akinator.setanswer(qkey, "Queen Victoria", defaultno)
    akinator.setanswer(qkey, "PewDiePie", defaultno)
    akinator.setanswer(qkey, "Britney Spears", defaultno)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.setanswer(qkey, "Gandalf", defaultno)
    akinator.setanswer(qkey, "Hillary Clinton", defaultno)
    akinator.setanswer(qkey, "Nelson Mandela", defaultno)
    akinator.setanswer(qkey, "Pythagoras", defaultno)
    akinator.setanswer(qkey, "Spiderman", defaultno)
    akinator.setanswer(qkey, "Albert Einstein", defaultno)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.setanswer(qkey, "Marie Curie", defaultno)
    akinator.setanswer(qkey, "J. K. Rowling", defaultno)
    akinator.setanswer(qkey, "Usain Bolt", defaultno)
    akinator.setanswer(qkey, "Bill Gates", defaultno)
    akinator.setanswer(qkey, "Elon Musk", defaultno)
    akinator.setanswer(qkey, "Julius Caesar", defaultno)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultmaybe)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultyes)
    
    qkey = akinator.addquestion("Are they human?")
    akinator.setanswer(qkey, "Harry Potter", defaultyes)
    akinator.setanswer(qkey, "Donald Trump", defaultyes)
    akinator.setanswer(qkey, "Pikachu", defaultno)
    akinator.setanswer(qkey, "Heidi", defaultyes)
    akinator.setanswer(qkey, "Popeye", defaultyes)
    akinator.setanswer(qkey, "Queen Victoria", defaultyes)
    akinator.setanswer(qkey, "PewDiePie", defaultyes)
    akinator.setanswer(qkey, "Britney Spears", defaultyes)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.setanswer(qkey, "Gandalf", defaultmaybe)
    akinator.setanswer(qkey, "Hillary Clinton", defaultyes)
    akinator.setanswer(qkey, "Nelson Mandela", defaultyes)
    akinator.setanswer(qkey, "Pythagoras", defaultyes)
    akinator.setanswer(qkey, "Spiderman", defaultyes)
    akinator.setanswer(qkey, "Albert Einstein", defaultyes)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultyes)
    akinator.setanswer(qkey, "Marie Curie", defaultyes)
    akinator.setanswer(qkey, "J. K. Rowling", defaultyes)
    akinator.setanswer(qkey, "Usain Bolt", defaultyes)
    akinator.setanswer(qkey, "Bill Gates", defaultyes)
    akinator.setanswer(qkey, "Elon Musk", defaultyes)
    akinator.setanswer(qkey, "Julius Caesar", defaultyes)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultyes)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultyes)
    
    qkey = akinator.addquestion("Are they popular with children?")
    akinator.setanswer(qkey, "Harry Potter", defaultyes)
    akinator.setanswer(qkey, "Donald Trump", defaultno)
    akinator.setanswer(qkey, "Pikachu", defaultyes)
    akinator.setanswer(qkey, "Heidi", defaultyes)
    akinator.setanswer(qkey, "Popeye", defaultyes)
    akinator.setanswer(qkey, "Queen Victoria", defaultno)
    akinator.setanswer(qkey, "PewDiePie", defaultyes)
    akinator.setanswer(qkey, "Britney Spears", defaultmaybe)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.setanswer(qkey, "Gandalf", defaultmaybe)
    akinator.setanswer(qkey, "Hillary Clinton", defaultno)
    akinator.setanswer(qkey, "Nelson Mandela", defaultmaybe)
    akinator.setanswer(qkey, "Pythagoras", defaultno)
    akinator.setanswer(qkey, "Spiderman", defaultyes)
    akinator.setanswer(qkey, "Albert Einstein", defaultno)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.setanswer(qkey, "Marie Curie", defaultno)
    akinator.setanswer(qkey, "J. K. Rowling", defaultyes)
    akinator.setanswer(qkey, "Usain Bolt", defaultmaybe)
    akinator.setanswer(qkey, "Bill Gates", defaultno)
    akinator.setanswer(qkey, "Elon Musk", defaultno)
    akinator.setanswer(qkey, "Julius Caesar", defaultno)
    akinator.setanswer(qkey, "Pacman", defaultyes)
    akinator.setanswer(qkey, "Snow White", defaultyes)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultyes)
    
    qkey = akinator.addquestion("Are they an entertainer?")
    akinator.setanswer(qkey, "Harry Potter", defaultno)
    akinator.setanswer(qkey, "Donald Trump", defaultmaybe)
    akinator.setanswer(qkey, "Pikachu", defaultno)
    akinator.setanswer(qkey, "Heidi", defaultno)
    akinator.setanswer(qkey, "Popeye", defaultno)
    akinator.setanswer(qkey, "Queen Victoria", defaultno)
    akinator.setanswer(qkey, "PewDiePie", defaultyes)
    akinator.setanswer(qkey, "Britney Spears", defaultyes)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.setanswer(qkey, "Gandalf", defaultno)
    akinator.setanswer(qkey, "Hillary Clinton", defaultno)
    akinator.setanswer(qkey, "Nelson Mandela", defaultno)
    akinator.setanswer(qkey, "Pythagoras", defaultno)
    akinator.setanswer(qkey, "Spiderman", defaultno)
    akinator.setanswer(qkey, "Albert Einstein", defaultno)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultyes)
    akinator.setanswer(qkey, "Marie Curie", defaultno)
    akinator.setanswer(qkey, "J. K. Rowling", defaultno)
    akinator.setanswer(qkey, "Usain Bolt", defaultno)
    akinator.setanswer(qkey, "Bill Gates", defaultno)
    akinator.setanswer(qkey, "Elon Musk", defaultno)
    akinator.setanswer(qkey, "Julius Caesar", defaultno)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultno)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they a politician?")
    akinator.setanswer(qkey, "Harry Potter", defaultno)
    akinator.setanswer(qkey, "Donald Trump", defaultyes)
    akinator.setanswer(qkey, "Pikachu", defaultno)
    akinator.setanswer(qkey, "Heidi", defaultno)
    akinator.setanswer(qkey, "Popeye", defaultno)
    akinator.setanswer(qkey, "Queen Victoria", defaultmaybe)
    akinator.setanswer(qkey, "PewDiePie", defaultno)
    akinator.setanswer(qkey, "Britney Spears", defaultno)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.setanswer(qkey, "Gandalf", defaultno)
    akinator.setanswer(qkey, "Hillary Clinton", defaultyes)
    akinator.setanswer(qkey, "Nelson Mandela", defaultyes)
    akinator.setanswer(qkey, "Pythagoras", defaultno)
    akinator.setanswer(qkey, "Spiderman", defaultno)
    akinator.setanswer(qkey, "Albert Einstein", defaultno)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.setanswer(qkey, "Marie Curie", defaultno)
    akinator.setanswer(qkey, "J. K. Rowling", defaultno)
    akinator.setanswer(qkey, "Usain Bolt", defaultno)
    akinator.setanswer(qkey, "Bill Gates", defaultno)
    akinator.setanswer(qkey, "Elon Musk", defaultno)
    akinator.setanswer(qkey, "Julius Caesar", defaultmaybe)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultno)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they American?")
    akinator.setanswer(qkey, "Harry Potter", defaultno)
    akinator.setanswer(qkey, "Donald Trump", defaultyes)
    akinator.setanswer(qkey, "Pikachu", defaultno)
    akinator.setanswer(qkey, "Heidi", defaultno)
    akinator.setanswer(qkey, "Popeye", defaultyes)
    akinator.setanswer(qkey, "Queen Victoria", defaultno)
    akinator.setanswer(qkey, "PewDiePie", defaultno)
    akinator.setanswer(qkey, "Britney Spears", defaultyes)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.setanswer(qkey, "Gandalf", defaultno)
    akinator.setanswer(qkey, "Hillary Clinton", defaultyes)
    akinator.setanswer(qkey, "Nelson Mandela", defaultno)
    akinator.setanswer(qkey, "Pythagoras", defaultno)
    akinator.setanswer(qkey, "Spiderman", defaultyes)
    akinator.setanswer(qkey, "Albert Einstein", defaultmaybe)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultyes)
    akinator.setanswer(qkey, "Marie Curie", defaultno)
    akinator.setanswer(qkey, "J. K. Rowling", defaultno)
    akinator.setanswer(qkey, "Usain Bolt", defaultno)
    akinator.setanswer(qkey, "Bill Gates", defaultyes)
    akinator.setanswer(qkey, "Elon Musk", defaultmaybe)
    akinator.setanswer(qkey, "Julius Caesar", defaultno)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultno)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they considered attractive?")
    akinator.setanswer(qkey, "Harry Potter", defaultmaybe)
    akinator.setanswer(qkey, "Donald Trump", defaultno)
    akinator.setanswer(qkey, "Pikachu", defaultno)
    akinator.setanswer(qkey, "Heidi", defaultno)
    akinator.setanswer(qkey, "Popeye", defaultmaybe)
    akinator.setanswer(qkey, "Queen Victoria", defaultno)
    akinator.setanswer(qkey, "PewDiePie", defaultmaybe)
    akinator.setanswer(qkey, "Britney Spears", defaultmaybe)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.setanswer(qkey, "Gandalf", defaultno)
    akinator.setanswer(qkey, "Hillary Clinton", defaultno)
    akinator.setanswer(qkey, "Nelson Mandela", defaultno)
    akinator.setanswer(qkey, "Pythagoras", defaultno)
    akinator.setanswer(qkey, "Spiderman", defaultyes)
    akinator.setanswer(qkey, "Albert Einstein", defaultno)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultyes)
    akinator.setanswer(qkey, "Marie Curie", defaultno)
    akinator.setanswer(qkey, "J. K. Rowling", defaultmaybe)
    akinator.setanswer(qkey, "Usain Bolt", defaultmaybe)
    akinator.setanswer(qkey, "Bill Gates", defaultno)
    akinator.setanswer(qkey, "Elon Musk", defaultmaybe)
    akinator.setanswer(qkey, "Julius Caesar", defaultno)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultyes)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are the considered intelligent or wise?")
    akinator.setanswer(qkey, "Harry Potter", defaultno)
    akinator.setanswer(qkey, "Donald Trump", defaultno)
    akinator.setanswer(qkey, "Pikachu", defaultno)
    akinator.setanswer(qkey, "Heidi", defaultno)
    akinator.setanswer(qkey, "Popeye", defaultno)
    akinator.setanswer(qkey, "Queen Victoria", defaultyes)
    akinator.setanswer(qkey, "PewDiePie", defaultno)
    akinator.setanswer(qkey, "Britney Spears", defaultno)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.setanswer(qkey, "Gandalf", defaultyes)
    akinator.setanswer(qkey, "Hillary Clinton", defaultmaybe)
    akinator.setanswer(qkey, "Nelson Mandela", defaultmaybe)
    akinator.setanswer(qkey, "Pythagoras", defaultyes)
    akinator.setanswer(qkey, "Spiderman", defaultno)
    akinator.setanswer(qkey, "Albert Einstein", defaultyes)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultmaybe)
    akinator.setanswer(qkey, "Marie Curie", defaultyes)
    akinator.setanswer(qkey, "J. K. Rowling", defaultyes)
    akinator.setanswer(qkey, "Usain Bolt", defaultmaybe)
    akinator.setanswer(qkey, "Bill Gates", defaultyes)
    akinator.setanswer(qkey, "Elon Musk", defaultyes)
    akinator.setanswer(qkey, "Julius Caesar", defaultmaybe)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultno)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Did they live in ancient times?")
    akinator.setanswer(qkey, "Harry Potter", defaultno)
    akinator.setanswer(qkey, "Donald Trump", defaultno)
    akinator.setanswer(qkey, "Pikachu", defaultno)
    akinator.setanswer(qkey, "Heidi", defaultno)
    akinator.setanswer(qkey, "Popeye", defaultno)
    akinator.setanswer(qkey, "Queen Victoria", defaultno)
    akinator.setanswer(qkey, "PewDiePie", defaultno)
    akinator.setanswer(qkey, "Britney Spears", defaultno)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.setanswer(qkey, "Gandalf", defaultmaybe)
    akinator.setanswer(qkey, "Hillary Clinton", defaultno)
    akinator.setanswer(qkey, "Nelson Mandela", defaultno)
    akinator.setanswer(qkey, "Pythagoras", defaultyes)
    akinator.setanswer(qkey, "Spiderman", defaultno)
    akinator.setanswer(qkey, "Albert Einstein", defaultno)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.setanswer(qkey, "Marie Curie", defaultno)
    akinator.setanswer(qkey, "J. K. Rowling", defaultno)
    akinator.setanswer(qkey, "Usain Bolt", defaultno)
    akinator.setanswer(qkey, "Bill Gates", defaultno)
    akinator.setanswer(qkey, "Elon Musk", defaultno)
    akinator.setanswer(qkey, "Julius Caesar", defaultyes)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultmaybe)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they a scientist or mathematician?")
    akinator.setanswer(qkey, "Harry Potter", defaultno)
    akinator.setanswer(qkey, "Donald Trump", defaultno)
    akinator.setanswer(qkey, "Pikachu", defaultno)
    akinator.setanswer(qkey, "Heidi", defaultno)
    akinator.setanswer(qkey, "Popeye", defaultno)
    akinator.setanswer(qkey, "Queen Victoria", defaultno)
    akinator.setanswer(qkey, "PewDiePie", defaultno)
    akinator.setanswer(qkey, "Britney Spears", defaultno)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.setanswer(qkey, "Gandalf", defaultno)
    akinator.setanswer(qkey, "Hillary Clinton", defaultno)
    akinator.setanswer(qkey, "Nelson Mandela", defaultno)
    akinator.setanswer(qkey, "Pythagoras", defaultyes)
    akinator.setanswer(qkey, "Spiderman", defaultno)
    akinator.setanswer(qkey, "Albert Einstein", defaultyes)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.setanswer(qkey, "Marie Curie", defaultyes)
    akinator.setanswer(qkey, "J. K. Rowling", defaultno)
    akinator.setanswer(qkey, "Usain Bolt", defaultno)
    akinator.setanswer(qkey, "Bill Gates", defaultmaybe)
    akinator.setanswer(qkey, "Elon Musk", defaultmaybe)
    akinator.setanswer(qkey, "Julius Caesar", defaultno)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultno)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Are they based on an animal?")
    akinator.setanswer(qkey, "Harry Potter", defaultno)
    akinator.setanswer(qkey, "Donald Trump", defaultno)
    akinator.setanswer(qkey, "Pikachu", defaultyes)
    akinator.setanswer(qkey, "Heidi", defaultno)
    akinator.setanswer(qkey, "Popeye", defaultno)
    akinator.setanswer(qkey, "Queen Victoria", defaultno)
    akinator.setanswer(qkey, "PewDiePie", defaultno)
    akinator.setanswer(qkey, "Britney Spears", defaultno)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultno)
    akinator.setanswer(qkey, "Gandalf", defaultno)
    akinator.setanswer(qkey, "Hillary Clinton", defaultno)
    akinator.setanswer(qkey, "Nelson Mandela", defaultno)
    akinator.setanswer(qkey, "Pythagoras", defaultno)
    akinator.setanswer(qkey, "Spiderman", defaultyes)
    akinator.setanswer(qkey, "Albert Einstein", defaultno)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultno)
    akinator.setanswer(qkey, "Marie Curie", defaultno)
    akinator.setanswer(qkey, "J. K. Rowling", defaultno)
    akinator.setanswer(qkey, "Usain Bolt", defaultno)
    akinator.setanswer(qkey, "Bill Gates", defaultno)
    akinator.setanswer(qkey, "Elon Musk", defaultno)
    akinator.setanswer(qkey, "Julius Caesar", defaultno)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultno)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultno)
    
    qkey = akinator.addquestion("Do they appear as a main character in a movie?")
    akinator.setanswer(qkey, "Harry Potter", defaultyes)
    akinator.setanswer(qkey, "Donald Trump", defaultno)
    akinator.setanswer(qkey, "Pikachu", defaultyes)
    akinator.setanswer(qkey, "Heidi", defaultyes)
    akinator.setanswer(qkey, "Popeye", defaultyes)
    akinator.setanswer(qkey, "Queen Victoria", defaultyes)
    akinator.setanswer(qkey, "PewDiePie", defaultno)
    akinator.setanswer(qkey, "Britney Spears", defaultno)
    akinator.setanswer(qkey, "Leonardo DiCaprio", defaultyes)
    akinator.setanswer(qkey, "Gandalf", defaultyes)
    akinator.setanswer(qkey, "Hillary Clinton", defaultno)
    akinator.setanswer(qkey, "Nelson Mandela", defaultyes)
    akinator.setanswer(qkey, "Pythagoras", defaultno)
    akinator.setanswer(qkey, "Spiderman", defaultyes)
    akinator.setanswer(qkey, "Albert Einstein", defaultno)
    akinator.setanswer(qkey, "Marilyn Monroe", defaultyes)
    akinator.setanswer(qkey, "Marie Curie", defaultno)
    akinator.setanswer(qkey, "J. K. Rowling", defaultno)
    akinator.setanswer(qkey, "Usain Bolt", defaultno)
    akinator.setanswer(qkey, "Bill Gates", defaultno)
    akinator.setanswer(qkey, "Elon Musk", defaultno)
    akinator.setanswer(qkey, "Julius Caesar", defaultyes)
    akinator.setanswer(qkey, "Pacman", defaultno)
    akinator.setanswer(qkey, "Snow White", defaultyes)
    akinator.setanswer(qkey, "Charlie from Charlie and the Chocolate Factory", defaultyes)
    
    for (character,qkey) in akinator.answerdict:
        if character not in akinator.characters:
            akinator.characters.append(character)
    akinator.numcharacters = len(akinator.characters)
    print("Characters: %d, questions %d" % (akinator.numcharacters, len(akinator.questions)))
    
    """
    for character in characters:
        qkey = akinator.addquestion("Is your character %s?" % character)
        for c in characters:
            akinator.answerdict[(c,qkey)] = [0.005, 0.005, 0.99]
        akinator.answerdict[(character,qkey)] = [0.99, 0.005, 0.005] 
    """
    akinator.stateprobs = np.ones(shape=(akinator.numcharacters))/akinator.numcharacters
    akinator.statelogprobs = np.ones(shape=(akinator.numcharacters))*-np.log(akinator.numcharacters)

if __name__== "__main__":    
    akinator = Akinator()
    initialise(akinator)
    questionno = 1
    while True:    
        qkey = akinator.nextquestion_entropy()   
        if qkey < 0:
            break
        akinator.usedquestions.append(qkey)
        answer = input("Q%d: %s " % (questionno, akinator.questions[qkey])).upper()
        akey = -1
        if answer.startswith("Y"):
            akey = YES
        elif answer.startswith("M"):
            akey = MAYBE
        elif answer.startswith("N"):
            akey = NO
        else:
            break
        akinator.update(qkey, akey)
        questionno += 1

